django_ecommerce/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, LogoutView, 
    PasswordResetView, PasswordResetConfirmView, 
    PasswordResetDoneView, PasswordResetCompleteView,
)
# import both app modules
from login import views as user_views
from shop import views as shop_views

# shop stuff
from shop.views import (
    ItemsView, ItemDetailView, OrderSummaryView, CheckoutView, PaymentView, 
    add_to_cart, remove_from_cart,
    add_single_to_cart, remove_single_from_cart, remove_all_from_cart,
)

# image view
from django.conf import settings
from django.conf.urls.static import static


# admin stuff
admin.site.site_title = 'Database'
admin.site.site_header = 'Red Star Django Admin'
admin.site.index_title = 'Red Star Site Admin'

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # home views
    path('', shop_views.home, name='home'),
    path('home/', shop_views.home_redirect, name='home_redirect'),

    # login
    path('login/', LoginView.as_view(template_name='login/login.html', redirect_authenticated_user=True), name="login"),
    path('register/', user_views.register, name="register"),

    # logout
    path('logout/', LogoutView.as_view(template_name='shop/home.html'), {'extra_context':{"page": "home", 'message':'True','message_title':'Logout: ','message_text':'You have logged out successfully'}}, name="logout"),

    # user profile
    path('profile/', user_views.profile, name='profile'),
    path('profile/edit/', user_views.edit_profile, name='edit_profile'),
    path('profile/password/', user_views.change_password, name='change_password'),

    # reset password
    path('reset_password/', PasswordResetView.as_view(template_name='login/resetpassword.html', email_template_name='login/reset_password_email.html'), name="password_reset"),
    path('reset_password/done/', PasswordResetDoneView.as_view(template_name='login/text.html'), name="password_reset_done"),
    path('reset_password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='login/change_password.html'), name="password_reset_confirm"),
    # redirect to login
    path('reset_password/complete/', PasswordResetCompleteView.as_view(template_name='shop/home.html'), {'extra_context':{"page": "home", 'message':'True','message_title':'Change Password: ','message_text':'You have successfully changed your password'}}, name="password_reset_complete"),

    # shop
    path('shop/', ItemsView.as_view(), name='item_list'),
    path('shop/product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('shop/add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('shop/remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),

    # after shopping
    path('cart/', login_required(OrderSummaryView.as_view()), name='cart'),
    path('checkout/', login_required(CheckoutView.as_view()), name='checkout'),

    # cart
    path('add_single_to_cart/<slug>/', add_single_to_cart, name='add_single_to_cart'),
    path('remove_single_from_cart/<slug>/', remove_single_from_cart, name='remove_single_from_cart'),
    path('remove_all_from_cart/<slug>/', remove_all_from_cart, name='remove_all_from_cart'),

    # payment
    path('payment/<payment_options>/', login_required(PaymentView.as_view()), name='payment')

]

# errors
handler400 = 'login.views.error_400_view'
handler403 = 'login.views.error_403_view'
handler404 = 'login.views.error_404_view'
handler500 = 'login.views.error_500_view'

# images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.shortcuts import reverse

# country
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('Tech', 'Technology'),
    ('Access', 'Accessories'),
    ('Trans', 'Transportation'),
    ('Misc', 'Other'),
)

LABEL_CHOICES = (
    ('N', 'New'),
    ('L', 'Limited'),
    ('S', 'Sold Out'),
)


class Item(models.Model):
    ''' the shopping item itself '''
    title = models.CharField(max_length=100)                                                        # name of product
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=50)                            # category
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True, null=True)            # label (optional)
    description = models.TextField(max_length=2500)                                                 # description of product
    image = models.ImageField(upload_to='images', blank=True, null=True)                            # product image
    price = models.DecimalField(max_digits=6, decimal_places=2, default=10)                         # price of item
    discounted_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)   # discounted price (optional)
    slug = models.SlugField()                                                                       # custom slag for item website

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return product website
        return reverse("product", kwargs={
            "slug": self.slug
        })

    def get_add_to_cart_url(self):
        ''' add item to cart '''
        return reverse("add_to_cart", kwargs={
            "slug": self.slug
        })

    def get_remove_from_cart_url(self):
        ''' removes item to cart '''
        return reverse("remove_from_cart", kwargs={
            "slug": self.slug
        })


class OrderItem(models.Model):
    ''' a list of ordered items '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)                                        # user
    item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True)                             # list of items
    quantity = models.IntegerField(default=1)                                                       # how many items there are
    ordered = models.BooleanField(default=False)                                                    # is order

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        ''' calculates the total price of items '''
        # if has a discount price
        if self.item.discounted_price:
            return self.quantity * self.item.discounted_price
        return self.quantity * self.item.price


class Order(models.Model):
    ''' the order itself '''
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)     # user
    items = models.ManyToManyField(OrderItem)                               # list of items belonging to user
    start_date = models.DateTimeField(auto_now_add=True)                    # start of first order
    ordered_date = models.DateTimeField()                                   # order date
    ordered = models.BooleanField(default=False)                            # is order

    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)                            # billing address

    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)                                            # pay

    def __str__(self):
        return self.user.username

    def get_final_price(self):
        ''' gets the final price of purchases '''
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()

        return total


class BillingAddress(models.Model):
    ''' handling billing address '''
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)     # user
    street_address = models.CharField(max_length=400)
    apartment_address = models.CharField(max_length=400)
    country = CountryField(multiple=False)
    zip_address = models.CharField(max_length=40)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    ''' for when a customer pays '''
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)     # user
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username

shop/forms.py
from django import forms
# country
from django_countries.fields import CountryField

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    street_address = forms.CharField(max_length=400)
    apartment_address = forms.CharField(max_length=400, required=False)
    country = CountryField(blank_label='(select country)').formfield()
    zip_address = forms.CharField(max_length=40)

    # options
    payment_options = forms.ChoiceField(widget=forms.RadioSelect(), choices=PAYMENT_CHOICES)

templates/shop/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Cart {% endblock title %}

{% block style %}
<style>
    /* body */
    .container {
        padding-bottom: 30px;
    }
    
    /* text */
    h1 {
        padding-top: 50px;
        padding-bottom: 25px;
    }
    h2 {
        padding-top: 50px;
        padding-bottom: 20px;
        font-size: 3em;
    }
    
    /* forms */
    .btn {
        margin-top: 20px;
    }
    .table > tbody > tr > .highrow {
        border-top: 3px solid;
    }

    /* btn */
    .checkout_btn, .continue_btn {
        margin-top: 0px;
    }

    .continue_btn {
        margin-right: 20px;
    }
</style>
{% endblock style %}

{% block cart_active %} active {% endblock cart_active %}

{% block banner %}

<!-- cart message -->
{% if messages %}

{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible alert-notification" role="alert">
    {{ message }}
    <button type="button" class="close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endblock banner %}

{% block text %}

<!-- order summary -->
<div class="container shadow-lg">
<!-- title -->
<h1>Order Summary:</h1>
<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-condensed">
            <!-- column names -->
            <thead>
                <tr>
                    <td><strong>Item Name</strong></td>
                    <td class="text-center"><strong>Item Price</strong></td>
                    <td class="text-center"><strong>Quantity</strong></td>
                    <td class="text-right"><strong>Item Total</strong></td>
                </tr>
            </thead>
            <tbody>

            <!-- items -->
            {% for order_item in object.items.all %}
                <tr>
                    <td>{{ order_item.item.title }}</td>
                    <td class="text-center">{{ order_item.item.price }}</td>
                    <td class="text-center">
                        <!-- +/- icons -->
                        <a href="{% url 'remove_single_from_cart' order_item.item.slug %}"><i><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-dash align-baseline" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3.5 8a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.5-.5z"/>
                        </svg></i></a>
                        {{ order_item.quantity }}
                        <a href="{% url 'add_single_to_cart' order_item.item.slug %}"><i><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus align-baseline" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                            <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                        </svg></i></a>
                    </td>
                    <td class="text-right">${{ order_item.get_total_item_price }}</td>
                    <!-- trash can -->
                    <td class="text-right">
                        <a href="{% url 'remove_all_from_cart' order_item.item.slug %}" style='color:red;'><i><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg></i></a>
                    </td>
                </tr>
            {% endfor %}

                <!-- totals -->
                <tr>
                    <td class="highrow"></td>
                    <td class="highrow"></td>
                    <td class="highrow text-center"><strong>Total</strong></td>
                    <td class="highrow text-right"><strong>${{ object.get_final_price }}</strong></td>
                    <td class="highrow"></td>
                </tr>
            </tbody>
        </table>

        <!-- buttons -->
        <div>
            <a href="{% url 'checkout' %}" class="btn btn-success float-right checkout_btn">Proceed to Checkout</a>
            <a href="{% url 'item_list' %}" class="btn btn-primary float-right continue_btn">Continue Shopping</a>
        </div>
    </div>
</div>
</div>

{% endblock text %}

{% block scripts %}
<script>
    // when document loads, slide alert down
    $(document).ready(function() {
        $(".alert").slideDown();
    });

    // once close is clicked, slide up the alert
    $(".close").click(function(){
        $(".alert").slideUp();
    });
</script>
{% endblock scripts %}

templates/shop/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Checkout {% endblock %}

{% block style %}
<style>
    /* body */
    .main {
        margin-top: 5vh;
    }

    /* text */
    h1 {
        padding-top: 50px;
        padding-bottom: 25px;
    }
    h2 {
        padding-top: 50px;
        padding-bottom: 20px;
        font-size: 3em;
    }

    .address {
        padding-left: 10px;
    }
    .checkout_form {
        padding: 10px;
    }
</style>

{% endblock style %}

{% block cart_active %} active {% endblock cart_active %}

{% block text %}
{% load crispy_forms_tags %}
<!-- Checkout Form -->
<div class="container shadow-lg">

<!-- header -->
<h2 class="my-5 h2 text-center">Checkout form</h2>

<div class="row"><div class="col-md-12 mb-4">

<div class="card">

    <!-- form -->
    <form method="POST" class='checkout_form'>
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
    </form>
</div>
</div>
</div></div>
{% endblock text %}

{% block scripts %}
<script>
$(document).ready(function() {
    $('.form-check input').last().prop('disabled', true) // disable paypal
    $('.form-check').last().append(`<br><small>Paypal will be impliemented later</small>`)
})
</script>
{% endblock scripts %}

templates/shop/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block style %}
<!-- swiper carousel http://idangero.us/swiper/demos/200-infinite-loop.html -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css">

<style>
    /* body */
    .main {
        margin-top: 5vh;
        margin-bottom: 2vh;
    }

    /* carousel */
    .swiper-pagination-bullet {
        transition: .3s;
    }
    .swiper-pagination-bullet:hover {
        transition: .3s;
        background-color: rgb(137, 182, 255);
    }
</style>
{% endblock style %}

{% block banner %}

<!-- alert for when you log out -->
{% if extra_context.message %}
<div class="alert alert-success alert-dismissible alert-notification" role="alert">
    <strong>{{ extra_context.message_title }}</strong> {{ extra_context.message_text }}
    <button type="button" class="close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<!-- payment message -->
{% if messages %}

{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible alert-notification" role="alert">
    {{ message }}
    <button type="button" class="close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><a href="{% url 'login' %}"></a><img src="{% static 'login/images/loc.png' %}" alt="Grand Opening"></div>
        <div class="swiper-slide"><a href="{% url 'login' %}"><img src="{% static 'login/images/pay.png' %}" alt="Greatest Deals in the country" title="Greatest Deals in the Country"></a></div>
        <div class="swiper-slide"><a href="{% url 'register' %}" class='overflow: hiddent'><img src="{% static 'login/images/j.png' %}" alt="Login in today for free" title="Login Now"></a></div>
        {% comment %} <div class="swiper-slide"><a href="{% url 'register' %}"><img src="{% static 'login/images/opening3.svg' %}" alt="Sign up today" title="Sign Up"></a></div> {% endcomment %}
    </div>

{% endblock banner %}

{% block text %} 

<!-- about this site -->
<h1>crenaul</h1>
<p><br>With us to star</p>


<!-- TODO: some products from the shop -->
<div class="products">
    <h2>Shop</h2>
    <br>
    <p>Start buy things now <a href="{% url 'item_list' %}">here</a></p>
</div>

{% endblock text %}


{% block scripts %}
<!-- swiper carousel http://idangero.us/swiper/demos/200-infinite-loop.html -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.min.js"></script>
<script>
    // swiper settings
    var swiper = new Swiper('.swiper-container', {
        spaceBetween: 0,
        centeredSlides: true,
        loop: true,
    autoplay: {
        delay: 4200,
        disableOnInteraction: false,
    },
    pagination: {
        el: '.swiper-pagination',
        clickable: true,
    },
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
        },
    });

    $(document).ready(function() {
        $(".alert").slideDown();

        // get swiper
        var mySwiper = document.querySelector('.swiper-container').swiper

        // pause and resume swiper when entering and exiting the slider with mouse
        $(".swiper-container").mouseenter(function() {
            mySwiper.autoplay.stop();
        });
        $(".swiper-container").mouseleave(function() {
            mySwiper.autoplay.start();
        });
    });

    $(".close").click(function(){
        $(".alert").slideUp();
    });
</script>

{% endblock scripts %}

templates/shop/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Product {% endblock %}

{% block style %}
<style>
    /* body */
    .main {
        margin-top: 5vh;
    }

    /* title */
    h1 {
        padding-bottom: 10px;
    }

    /* carousel */
    .swiper-pagination-bullet {
        transition: .3s;
    }
    .swiper-pagination-bullet:hover {
        transition: .3s;
        background-color: rgb(137, 182, 255);
    }

    /* btns */
    .carts a {
        margin-right: 10px;
    }

    /* image */
    .product_image {
        padding: 1.5rem!important;
    }
</style>
{% endblock style %}

{% block shop_active %} active {% endblock shop_active %}

{% block banner %}

<!-- cart message -->
{% if messages %}

{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible alert-notification" role="alert">
    {{ message }}
    <button type="button" class="close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endblock banner %}

{% block text %}
<div class="container dark-grey-text mt-5">
<h1> {{ item.title }} </h1>
<div class="row wow fadeIn">

    <!-- product image -->
    <div class="col-md-6 mb-4 product_image">
    {% if item.image %}
        <img src="{{ item.image.url }}" class="img-fluid" alt="">
    {% else %}
        <img src="{% static 'login/images/idk.png' %}" class="img-fluid" alt="" style='max-height: 300px;'>
    {% endif %}
    </div>

    <div class="col-md-6 mb-4">
    <div class="p-4 item-description">

        <!-- product item badge -->
        <div class="mb-3">
            <a href="">
                <span class="badge badge-secondary">{{ item.get_category_display }}</span>
            </a>
        </div>

        <!-- product item price -->
        <p class="lead">
        <!-- discount if it applies -->
        {% if item.discounted_price %}
            <span class="mr-1">
                <del>${{ item.price }}</del>
                <span>${{ item.discounted_price }}</span>
            </span>
        {% else %}
            <span>${{ item.price }}</span>
        {% endif %}</span>
        </p>

        <!-- item descriptions -->
        <p class="lead font-weight-bold">Description</p>
        <p>{{ item.description }}</p>
        <br>

        <form class="d-flex justify-content-left carts">
            <!-- add to cart -->
            <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <!-- remove from cart -->
            <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                Remove from cart
            </a>
        </form>
    </div>
    </div>
</div>

<hr> <!-- divider -->

<!-- more products... -->
<div class="row d-flex justify-content-center wow fadeIn">
    <div class="col-md-6 text-center">
        <h4 class="my-4 h4">More Products</h4>
        <p> TODO: list of more products </p>
    </div>
</div>
</div>
{% endblock text %}

{% block scripts %}
<script>
    // when document loads, slide alert down
    $(document).ready(function() {
        $(".alert").slideDown();
    });

    // once close is clicked, slide up the alert
    $(".close").click(function(){
        $(".alert").slideUp();
    });
</script>
{% endblock scripts %}

templates/shop/shop.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Shop {% endblock %}

{% block style %}
<style>
    /* body */
    .main {
    margin-top: 5vh;
    }

    /* caracel */
    .swiper-pagination-bullet {
    transition: .3s;
    }
    .swiper-pagination-bullet:hover {
    transition: .3s;
    background-color: rgb(137, 182, 255);
    }

    /* colors */
    .grey-text {
    color: #b7b7b7!important;
    }
    .grey-text:hover {
    color: #8e8e8e!important
    }
    .dark-grey-text {
    color: #333232!important
    }
    .dark-grey-text:hover {
    color: #1c1b1b!important
    }
    .grey_hover:hover {
    color: #666666!important
    }

    /* mask */
    .mask {
    width: 100%;
    height: 100%;
    transition: .5s ease;
    opacity: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    text-align: center;
    }
    .overlay {
    width: 100%;
    position: relative;
    }
    .overlay:hover, .card-img-top {
    opacity: 0.3;
    }

    .overlay:hover .mask {
    opacity: 1;
    }

    /* other */
    .grey-text, .dark-grey-text, .grey-text:hover, .dark-grey-text:hover {
    text-decoration: none;
    }
    .linker {
    width: 100%;
    height: 100%;
    }

    /* transitions */
    .grey-text, .dark-grey-text, .grey-text:hover, 
    .dark-grey-text:hover, .overlay:hover, .card-img-top, 
    .overlay, .mask {
    transition: .2s;
    -moz-transition: .2s;
    -webkit-transition: .2s;
    -o-transition: .2s;
}
</style>
{% endblock style %}

{% block shop_active %} active {% endblock shop_active %}

{% block text %}
<div class="container">

<!-- Categories tab -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">

    <!-- navigation header -->
    <span class="nav-link transition">Categories:</span>

    <!-- hamburger tabs -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- catagories -->
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link transition" href="#">All
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link transition" href="#">Technology</a>
            </li>
            <li class="nav-item">
                <a class="nav-link transition" href="#">Accessories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link transition" href="#">Transportation</a>
            </li>
            <li class="nav-item">
                <a class="nav-link transition" href="#">Other</a>
            </li>
        </ul>
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    <!-- end of catagories -->
</nav>

<!-- products -->
<section class="text-center mb-4">
    <div class="row wow fadeIn">

        <!-- for each object, return it's card -->
        {% for item in object_list %}

        <!-- card -->
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <!-- card image -->
                <div class="view overlay preview_image_container">
                    {% if item.image %}
                        <img src="{{ item.image.url }}"
                            class="card-img-top" alt="">
                    {% else %}
                        <img src="{% static 'login/images/idk.png' %}"
                            class="card-img-top" alt="">
                    {% endif %}
                        <a href="{{ item.get_absolute_url }}" class="linker">
                            <div class="mask"></div>
                        </a>
                </div>

                <!-- card content -->
                <div class="card-body text-center">
                    <!-- category -->
                    <a href="" class="grey-text">
                        <h5>{{ item.get_category_display }}</h5>
                    </a>
                    <h5>
                        <!-- item name and badge -->
                        <strong>
                            <a href="{{ item.get_absolute_url }}"
                                class="dark-grey-text grey_hover">{{ item.title }}
                                {% if item.get_label_display == 'New' %}
                                <span class="badge badge-primary">New</span>
                                {% elif item.get_label_display == 'Limited' %}
                                <span class="badge badge-warning">Limited</span>
                                {% else %}
                                <span class="badge badge-dark">Sold out</span>
                                {% endif %}
                            </a>
                        </strong>
                    </h5>

                    <!-- price -->
                    <h4 class="font-weight-bold blue-text">
                        <strong>$
                            {% if item.discounted_price %}
                            {{ item.discounted_price }}
                            {% else %}
                            {{ item.price }}
                            {% endif %}
                        </strong>
                    </h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

<!-- page navigation -->

{% if is_paginated %}
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">

        <!-- left arrow shows if it has a previous page -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
        {% endif %}

        <!-- pages -->
        <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
            </a>
        </li>

        <!-- right arrow -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
</div>
{% endblock text %}